### ISSUE TITLE
Add option to skip versioning of js & css files

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/buffer-static-upload#12]
### Purpose
For us to be able to upload pre-hashed bundles and leverage code splitting w/ webpack or Next.js, we should allow the user to disable skip versioning of the js and css files.

### Notes
- We can't just detect an existing hash via `<filename>.<hash>.js` pattern b/c some assets like in Next.js are nested in a versioned directory instead (ex. `static/<version>/pages/<filename>.js`)
- For this to work we may need to add a flag such as `--skip-hash` or `--skip-versioning`
- I'm not sure if we'll have a mixed workflow where some files should be versions and some may not. If this is the case we may leave it to the end user to use this cli twice and stitch together the output

cc @msanroman

**Comment by msanroman** [comment]
Got #19 working on Analyze with the behavior you were mentioning in here.

A good one to think about is if we'd like this to be the default for everyone, as it would encourage good practices on code splitting and bundle management for every project. So maybe `buffer-static-upload@1.0.0` would either:

- Shift this pattern from being the opt-in behavior to be the default one, and still allow adding versioning here with `-with-versioning` flag.
- Remove versioning option altogether.

**Comment by djfarrelly** [comment]
Added in version 0.3.0: https://github.com/bufferapp/buffer-static-upload/releases/tag/0.3.0
